### ISSUE TITLE
Main Menu Resizing

### ISSUE THREAD

**Issue by EliCDavis** [Blond-in-Blue/Chicken-Nuggets#8]
On smaller screens the main menu becomes funky and text seems to disapear.
![screenshot 2015-10-31 10 49 27](https://cloud.githubusercontent.com/assets/9094977/10864728/2102953c-7fbd-11e5-883e-379cc982b58d.png)
Those dimensions are around 500 x 500.

**Comment by wesstr** [comment]
This should now be fixed in my latest commit.

**Comment by EliCDavis** [comment]
Sync your repo and PR brah

**Comment by EliCDavis** [comment]
Good Enough :+1:
